version: 0.2

phases:
  install:
    commands:
      - sudo apt-get update -y
      - sudo apt-get install -y nodejs npm
      - npm cache clean
      - npm config set strict-ssl false
      - npm install n -g
      - n 10.13.0
      - npm update -g npm
      - node -v
      - npm -v
      - apt-get purge -y nodejs
      # Install dependencies needed for running tests
      - npm ci
      - npm config set strict-ssl true
      - pip freeze > deletelist.txt
      - pip uninstall -r deletelist.txt
      - pip install -r requirements.txt
      - npm run build

  pre_build:
    commands:
      # Discover and run unit tests. For more information, see <https://docs.djangoproject.com/en/2.0/topics/testing/overview/>
      # - python manage.py test --settings config.settings.production
      # - npm run test:unit
      
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml