site_name: NARUKO
repo_url: https://github.com/crosspower/exam-pj
repo_name: GitHub
theme:
  name: 'material'
  language: 'ja'
extra:
  search:
    language: 'jp'
nav:
  - Home: 'index.md'
  - 環境構築: 'installation.md'
  - 開発者向け構築: 'developer.md'
