# Generated by Django 2.1.2 on 2019-01-11 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelephoneDestination',
            fields=[
                ('notificationdestinationmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.NotificationDestinationModel')),
                ('phone_number', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'telephone_destination',
            },
            bases=('backend.notificationdestinationmodel', models.Model),
        ),
    ]
