# Generated by Django 2.1.2 on 2019-02-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_operationlogmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='telephonedestination',
            name='country_code',
            field=models.IntegerField(default=81),
        ),
    ]
